version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 964146288621.dkr.ecr.eu-west-1.amazonaws.com

  pre_build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-docker-app .

  build:
    commands:
      - echo Tagging the Docker image...
      - docker tag my-docker-app:latest 964146288621.dkr.ecr.eu-west-1.amazonaws.com/test/my-flask-app:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 964146288621.dkr.ecr.eu-west-1.amazonaws.com/test/my-flask-app:latest
      - echo Build completed successfully.
